### ISSUE TITLE
zsh: permission denied: ./start

### ISSUE THREAD

**Issue by dougkusanagi** [darkterminal/turso-docker-php#1]
## Description

Hi, i followed the tutorial and just when i try to run the ./start i receive a `zsh: permission denied: ./start`. I also tried with bash but no success at all.

![Screenshot_6](https://github.com/user-attachments/assets/5c7b24eb-34ec-4bb8-ad25-052ffd257b13)

## Parallel question

I have another question and its probably a dumb one but... I'd like to know if the daemon service will be available on windows side too or i'll have to develop everything in wsl. Because i was hoping to use turso for a windows desktop experimentation with NativePHP. If i get right i can't because would be necessary to have you turso-docker-php running in every machine i installed my desktop app.

**Comment by darkterminal** [comment]
Hi @dougkusanagi Have you tried to make the `start` file executable with the command `chmod +x start`

> I have another question and its probably a dumb one but... I'd like to know if the daemon service will be available on windows side too or i'll have to develop everything in wsl. Because i was hoping to use turso for a windows desktop experimentation with NativePHP. If i get right i can't because would be necessary to have you turso-docker-php running in every machine i installed my desktop app.

Turso itself has no plans to support Windows, but you can use the Turso CLI on Windows WSL for development.

And I’m just a contributor to the Turso PHP ecosystem. I’d be happy to help you. Feel free to contact me directly via Discord at `.darkterminal`

**Comment by dougkusanagi** [comment]
Yeah! I knew it was a dumb thing... I do know about the chmod command but like i manly use windows, totally forgot that is required to exec files in linux. I thought the container would have the `liblibsql_php.so` built in but now i'm getting a warning that could not load dynamically the lib. Did i miss something?

![Screenshot_7](https://github.com/user-attachments/assets/0d5b9006-d30a-43a9-a04d-eb0af4c5758f)

I appreciate the quick response and availability for contact!

**Comment by darkterminal** [comment]
This issue is already solved. So, case closed... Thank you
